#!/bin/sh
set -eu
lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer none \
  --archive-areas "main contrib non-free-firmware" \
  --security true \
  --apt-recommends true \
  --bootappend-live "boot=live components quiet splash" \
  "${@}"
